### ISSUE TITLE
Adding CHARACTER SET and COLLATE for db:create

### ISSUE THREAD

**Issue by bilogic** [vkovic/laravel-commando#2]
Hi,

Please consider adding support for ```CHARACTER SET``` and ```COLLATE``` like this post here https://anthonysterling.com/posts/using-an-artisan-command-to-create-a-database-in-laravel-or-lumen.html

Thank you.

**Comment by vkovic** [comment]
Thanks for pointing that out. I'll incorporate the changes you suggested.
